### ISSUE TITLE
Chest dont have Texture

### ISSUE THREAD

**Issue by KSZLAGK** [PoeticRainbow/golden-days#12]
Chest when placed appear to be broken for some reason.

![2021-06-03_19 35 47](https://user-images.githubusercontent.com/32240709/120688560-7bc2a800-c4a3-11eb-8aa0-2cfe76b4c471.png)

Played on Minecraft 1.16.5 + Optifine

**Comment by PoeticRainbow** [comment]
Should be fixed in the most recent version of Golden Days (download from source).
