### ISSUE TITLE
Permission to repackage assets

### ISSUE THREAD

**Issue by helpimnotdrowning** [PoeticRainbow/golden-days#18]
I'm planning to put up my ""edit"" of Classic Alternative ( https://www.planetminecraft.com/texture-pack/classic-alternative/ ) as a Github repo, but somewhere along the line I've added an unknown number of files and stuff from Golden Days to it, and I have no idea what is from CA and what is from here. I don't know where else to ask the permission, so I'm asking here.

**Comment by PoeticRainbow** [comment]
Hey, sorry for not seeing this issue earlier.
Did you close this issue because you removed the assets, or elsewise?
