### ISSUE TITLE
Visibility issue with Deepslate Coal Ore and Netherite Ore

### ISSUE THREAD

**Issue by firealex90** [PoeticRainbow/golden-days#19]
![2021-08-11_13 45 17](https://user-images.githubusercontent.com/88802103/129103482-58191226-69ab-4c76-9dfe-e22869ef0985.png)
can you change or fix the textures for netherite and Blackstone coal ore. they are really hard to distinguish when mining.

**Comment by PoeticRainbow** [comment]
I will have to continue to think about the fix for the Netherite Ore

**Comment by PoeticRainbow** [comment]
![2023-11-03_23 36 02](https://github.com/PoeticRainbow/golden-days/assets/46388705/54b3e3b0-0253-493d-939f-e0be127585dd)
It's been far too long that I've left this suggestion here. I apologize for that.
If you still are here and care, how does this look?
