### ISSUE TITLE
Support for Enhanced Block Entities

### ISSUE THREAD

**Issue by Brottweiler** [PoeticRainbow/golden-days#20]
Hello!

Noticed you made an addon for FastChest; Enhanced Block Entities is a better mod, because it optimizes even more things. It makes beds, signs, bells into block entities, too, not just chests. EBE can also preserve the opening animation of chests, although that is not needed in this case.

I've written up a gist with all the textures and model files that are needed. If you want to use them go ahead. https://gist.github.com/Brottweiler/bc8ab16e473f3dc0f3a01c3086d65776

**Comment by PoeticRainbow** [comment]
I just added support for this mod. Sorry about the long wait!
