### ISSUE TITLE
Leather armor does not appear dyed

### ISSUE THREAD

**Issue by EH86055** [PoeticRainbow/golden-days#21]
I'm new to GitHub, so I'm sorry if this post is weird in any way. But yeah, as the title says—the item for grass blocks seems to show the side texture (dirt, with glass bit at the top) on all of its surfaces, and dyed leather armour doesn't appear coloured.
Anyway, that's all.

**Comment by arceuss** [comment]
go to assets\minecraft\textures\models\armor and delete leather overlays
this is a solution for bringing back dyed leather armor

**Comment by PoeticRainbow** [comment]
The grass block is intentional as that is how they looked in Beta 1.7.3. If I had a customizer, I'd let you choose that. The leather armor is intentional, but I am experimenting with ways to make undyed leather armor look like Beta, but allowing dying. I'll keep you posted.
