### ISSUE TITLE
Game is unplayable when using OptiFine or Colormatic

### ISSUE THREAD

**Issue by staticanimal** [PoeticRainbow/golden-days#23]
running 1.7.0 in game version 1.18.1 alongside optifine hd u h4 and fabric + optifabric

every single text string in the game turns invisible upon loading any map. f3+t does not fix it.

**Comment by TerminalHash** [comment]
The same as with a conventional Optfine, as with my Fabric modpack.

**Comment by ElBread3** [comment]
Yep, also having this issue. All inventory items are also black as well.

**Comment by Jordon87** [comment]
it happened to me so, it must be happening for probably everyone using Optifine with the pack.

hopefully this does get fixed soon.

**Comment by Brandon98SE** [comment]
Issue is still here, when using Colourmatic with this resourcepack it breaks Distant Horizons mod and if I use full-bright it inverts the colours if I have anything over 100% (default is 1600%)

**Comment by PoeticRainbow** [comment]
I believe I fixed this in 1.7.1
