### ISSUE TITLE
Golden Days Beta Pack has Inaccurate Water Coloring

### ISSUE THREAD

**Issue by StereoMadnessss** [PoeticRainbow/golden-days#27]
So I have a bone to pick with this pack. The water colors are inaccurate and I can fix it as I know resource packs very well but for others who spot this, this will not make the pack look appealing. The first image is the default pack and the second is the fixed version.
Before:
![2022-04-17_09 58 32](https://user-images.githubusercontent.com/77188051/163724737-4341d88e-6e28-4f51-9129-bcf711c174e3.png)
After:
![2022-04-17_09 58 58](https://user-images.githubusercontent.com/77188051/163724743-fc03cac0-9494-4200-a642-cdfdc420d4c0.png)

I made a fix for this as if you want to use it:
[waterfix.zip](https://github.com/PoeticRainbow/golden-days/files/8502058/waterfix.zip)
Put it in assets/minecraft/optifine/colormaps/custom.

Beta Water for Comparison:
<img width="851" alt="Screen Shot 2022-04-17 at 10 01 38 AM" src="https://user-images.githubusercontent.com/77188051/163724805-0adf3dbc-a851-4930-b8b2-80edd7784efc.png">

**Comment by PoeticRainbow** [comment]
The water in Golden Days does not depend on OptiFine. It uses a different technique. I don't know what version you're using in that first screenshot, but that is not the most updated version of Golden Days even by the time you posted this. I have a full-time job and do not have the time to develop Golden Days consistently.

**Comment by PoeticRainbow** [comment]
The water has been adjusted and is now a lot more accurate. This method still allows for water tinting.
