### ISSUE TITLE
Pack to hide hunger bar (and other UI elements that aren't in beta)

### ISSUE THREAD

**Issue by soshimee** [PoeticRainbow/golden-days#28]

**Comment by Ben1701A** [comment]
hmm. Perhapas this should be in a separate pack so that the base pack can still be usable with vanilla gameplay? Unless you wanted to be blindfolded about how hungry you were.

**Comment by pessoacasual12** [comment]
There is a Nostalgic Tweaks 2.0 version being worked on that adds gameplay tweaks, such as hunger and experience remover. It's still in beta, and can be only downloaded through the mod's Discord server.

**Comment by Secret-chest** [comment]
This can be in PicturePerfect
