### ISSUE TITLE
Improper Grass Block BlockState File

### ISSUE THREAD

**Issue by StereoMadnessss** [PoeticRainbow/golden-days#29]
In the latest version (and has been unpatched for quite a while in golden days), this bug has been a nuisance. As how easily fixable this is, there is no excuse.
![2022-08-11_17 53 22](https://user-images.githubusercontent.com/77188051/184265698-4e7bfd6b-c943-47c1-a7e4-9ae72b23fa97.png)

However, this is because the pack overwrites the .json file, making it unable to load the snowy variant and as such, uses the normal grass block model.

An easy fix to this mess is to replace the file with this:

(Fixed)

{
  "variants": {
    "snowy=false": [
      {
        "model": "minecraft:block/grass_block_snow"
      }
    ],
    "snowy=true": {
      "model": "minecraft:block/grass_block_snow"
    }
  }
}

To this:

(Original, Broken)

{
  "variants": {
    "snowy=false": [
      {
        "model": "minecraft:block/grass_block"
      }
    ]
  }
}

**Comment by PoeticRainbow** [comment]
Your version is outdated. The grass blockstate file works just fine.

![2022-08-12_15 37 01](https://user-images.githubusercontent.com/46388705/184430936-cd428f86-5c03-4a82-8654-a59cde3f50a5.png)
