### ISSUE TITLE
Chests, Enderchests, Trapped chests and Double chests textures bugged

### ISSUE THREAD

**Issue by Sydacei** [PoeticRainbow/golden-days#30]
![image](https://user-images.githubusercontent.com/114234054/191960713-38e62d17-9229-44e0-97ae-0a77c8ba5ac4.png)
![image](https://user-images.githubusercontent.com/114234054/191960770-bbd291dc-54bd-4578-9a5c-1e321a4ff333.png)

I'm not really sure what to make of this, but it'd be greatly appreciated if somebody has an explanation/fix for this

(i also added the two images above for reference - first one because i'm not 100% sure if the order that they're in matters, and the second one because i'm not exactly the best at explaining things)

**Comment by PoeticRainbow** [comment]
Provide your Minecraft version and mods installed please :)

**Comment by Sydacei** [comment]
> Provide your Minecraft version and mods installed please :)


Hi there, sorry for the very late reply, but here's the things you've asked for

![image](https://user-images.githubusercontent.com/114234054/193307803-3cfcd380-20f9-4e85-a9bd-3586e20d68d8.png)
![image](https://user-images.githubusercontent.com/114234054/193307878-29c7c356-ddd0-4e45-b543-65071aa50ed8.png)

**Comment by PoeticRainbow** [comment]
Sorry for ghosting you, I took a break.
Unfortunately since this version is older, I do not currently have plans to look into it. Obviously this was a while ago, I am not sure what the issue could be since that version should have the correct chest model.
