### ISSUE TITLE
Grass block icon is glitched in base pack

### ISSUE THREAD

**Issue by SDM0** [PoeticRainbow/golden-days#32]
The displayed icon for the grass block is incorrect (I have put the programmer pack between default and golden days)

![grass](https://user-images.githubusercontent.com/60699143/227682019-86079f2a-eda5-4546-9a08-aa0a681e42d7.png)

**Comment by robtech21** [comment]
I'm pretty sure this is intentional, due to the fact that the pack is centered around alpha/beta style textures

**Comment by PoeticRainbow** [comment]
Yep! This is intentional as in beta 1.7.3 that is how the grass block appeared due to it being unobtainable in survival. If you don't like it, just delete the grass_block.json in assets/minecraft/models/item/
