### ISSUE TITLE
Cobblestone texture

### ISSUE THREAD

**Issue by Michal0513** [PoeticRainbow/golden-days#33]
Hello I have problem with cobblestone texture, Even when i use alpha or base resource pack i still have NEW cobblestone texture, and I want a old alpha cobble texture. Can someone help?

**Comment by PoeticRainbow** [comment]
That's strange. It works fine for me? Double check the order you have the packs and make sure you are up to date!
![image](http
![2023-03-29_13 34 01](https://user-images.githubusercontent.com/46388705/228621292-f2f14c18-a313-4d19-a215-9638785cbc7b.png)
s://user-images.githubusercontent.com/46388705/228621188-f30cbecb-fb88-4a5f-80cf-42c4a80bb5a9.png)

**Comment by PoeticRainbow** [comment]
Due to inactivity, I assume you have this resolved. Reopen if needed.
