### ISSUE TITLE
cooked porkchop texture same as cooked steak

### ISSUE THREAD

**Issue by SpongeBucket** [PoeticRainbow/golden-days#34]
Hi, I'm honestly not sure if this was just how it was for beta Minecraft but the cooked porkchop texture is the same as the cooked steak and can be confusing when stacking items. Honestly a very minor thing but just thought I'd bring it to your attention, thanks!

**Comment by PoeticRainbow** [comment]
This is intentional as Cooked Porkchop used to look like Steak. I might consider doing something to address this if it is enough of an issue.

**Comment by PoeticRainbow** [comment]
I have went back on this and decided to make the Cooked Porkchop the texture from Beta 1.8 to avoid confusion between Cooked Porkchop and Steak.
