### ISSUE TITLE
Torso of the cow model is rotate incorrectly (OptiFine - 1.20.1)

### ISSUE THREAD

**Issue by Mati0331** [PoeticRainbow/golden-days#35]
![image](https://github.com/PoeticRainbow/golden-days/assets/138071197/160206b8-9da5-4052-8fab-7287cb7ef067)
nothing else used besides optifine, anyone else facing this problem?

**Comment by wedoalargeamountoftrolling** [comment]
yeah im facing the same bug as well

**Comment by Mati0331** [comment]
by the way, until its properly fixed just get rid of the cow.jem file

**Comment by Mati0331** [comment]
> yeah im facing the same bug as well

by the way until it has a proper fix just get rid of the cow.jem file

**Comment by Mati0331** [comment]
> yeah im facing the same bug as well

btw until its fixed jus get rid of the cow.jem file

**Comment by LitsyPorksulum** [comment]
> > yeah im facing the same bug as well
> 
> btw until its fixed jus get rid of the cow.jem file

howd i do that

**Comment by PoeticRainbow** [comment]
I fixed this and never released the fix.

**Comment by PoeticRainbow** [comment]
This is now working on Entity Model Features, could I have someone test this with OptiFine? I do not use it myself.

**Comment by chickenboi-09** [comment]
> This is now working on Entity Model Features, could I have someone test this with OptiFine? I do not use it myself.

it's still broken on optifine

**Comment by Nukiloco** [comment]
I'm having the same issue on 1.18.2.

**Comment by PoeticRainbow** [comment]
@Nukiloco What mod are you using for the entity models? CEM, or EMF?

**Comment by PoeticRainbow** [comment]
The current cow model is working fine on both 1.20.1 with EMF and with OptiFine.
This version has not been released, you need to download it from the source here until I release it.
![2023-08-17_11 45 18](https://github.com/PoeticRainbow/golden-days/assets/46388705/b16e98e6-8100-4624-ab3d-3bb98fe4dca6)
![2023-08-17_15 45 19](https://github.com/PoeticRainbow/golden-days/assets/46388705/923fdab7-2fdd-46ab-bb86-aa1f994faf99)
