### ISSUE TITLE
Mojang Studios text is not replaced (1.19.4)

### ISSUE THREAD

**Issue by FlintsCousin** [PoeticRainbow/golden-days#36]
It's pretty annoying for me because I like the authenticity of old Minecraft.
<img width="430" alt="Screenshot 2023-07-03 215534" src="https://github.com/PoeticRainbow/golden-days/assets/138543048/eb9f2391-1b24-4c84-b8f7-5a8e5f9b849d">

**Comment by PoeticRainbow** [comment]
It seems that I am not allowed to replace this image anymore. I will have to look into it more, as I am not finding any documentation on it.
