### ISSUE TITLE
Grass seems to be white.

### ISSUE THREAD

**Issue by ldx1u** [PoeticRainbow/golden-days#37]
I dunno why this is happening, i use Nostalgic Tweaks so i thought that was the cause and i tried disabling it and this still happens. This only happens when i use alpha pack with base.
![2023-07-10_13 43 48](https://github.com/PoeticRainbow/golden-days/assets/114127384/08fef912-1c13-4614-95d3-b4f4b7196740)

**Comment by coreycusick** [comment]
I had this same issue at first, the alpha texture pack has to be on top.

**Comment by PoeticRainbow** [comment]
As the person above says, make sure you follow the instructions for the order of the packs on the resource packs screen. The load order does matter, as the ones on top will replace textures and models in the ones below. Add-ons always go ABOVE base.
