### ISSUE TITLE
Inconsistent textures and ones that should be updated

### ISSUE THREAD

**Issue by PMan56789** [PoeticRainbow/golden-days#38]
Golden Days is my favourite Beta resource pack for Minecraft, and I particularly love its unique textures that have been adapted from modern ones. However, there are a few textures in the pack that remain inconsistent to others, as well as ones which aren't accurate to how they were in Alpha/Beta. Here I will list a few incosistent/missing textures and why they should be fixed.

- Netherite and Copper: In the Alpha pack, Netherite and Copper have not been updated to resemble other Alpha storage block textures. These would simply need an update to more closely resemble the other block textures such as Gold, Iron and Diamonds.
- Rails: Rails had a slightly different texture that was used from Infdev until Alpha 1.2 when it was changed, so I believe that the old texture should be brought back, even if it has minor differences. This would likely also apply to other rail blocks such as Activator, Detector and maybe Powered Rails.
- Red Sand: Sand had a slightly different texture in Beta, which is present in the pack, but Red Sand has not been updated in accordance with the old Sand texture, so I think that it should also be changed.
- Red Sandstone: Similarly, Sandstone also had a slightly different texture in Beta Minecraft, so Red Sandstone I think should also be changed in accordance with the Beta Sandstone.
- Grass Paths, Podzols and Coarse Dirt: Again, these textures are not consistent with the old Dirt texture as they use the bottom half of the modern texture, so I think they should be updated.
- Concrete, Glazed Terracotta and Concrete Powder: These textures should be updated to more closesly the Beta wool colours, as currently they use the 1.12 colours. It seems that Candles and Beds have already been changed, so I think this would be the next logical step.
- Stripped Mangrove Log Top: Bizarrely, it doesn't seem that this block uses the old Log top texture, which is strange as the normal Mangrove Logs have been updated to use the older texture.
- End Portal Side: The End Portal side should be updated to use the End Stone texture used in the pack, which is an inverted Cobblestone texture.
- Opinionated Changes: Lastly, while I don't think changing these textures are a high priority as they aren't really that inconsistent with others, I think that, firstly, Stained Glasses should be changed to the textures used in 13w41a, as I feel those are more Beta-like. Secondly, I think Blue Ice should be changed to something more similar to regular Ice/Packed Ice, since I think it currently looks nothing like them (although at the time it was added, the old Ice/Packed Ice textures were still being used). Finally, I think that the Coral textures should be changed to something similar to how they looked in 1.13 development footage, which I also think looked a lot more Beta-like: https://minecraft.fandom.com/wiki/History_of_textures#Blocks_2

I hope you take my suggestions into consideration, and hopefully that wasn't too much!

**Comment by PoeticRainbow** [comment]
I have implemented quite a few of these changes. I am going to look into the coral more, as I want it to be vanilla friendly color wise but still have an old theme. Thank you so much for the suggestions!
