### ISSUE TITLE
[Feature] Make chests full blocks

### ISSUE THREAD

**Issue by Moresteck** [PoeticRainbow/golden-days#40]
**Description of the feature**:
Chests should be a full block, to match how they are in b1.7.3.
Currently, chests have their texture changed to mimic that of Beta, but they still don't occupy the whole block AND they have the opening/closing animations & sounds.

**Comment by tapok282008** [comment]
Just... Just use nostalgic tweaks... It's not that hard, and there is a lot more features in it.

**Comment by PoeticRainbow** [comment]
> Apologies for asking to make the resourcepack better.

Sorry for not getting back to you sooner. This pack does support making chests full size blocks. It requires Enhanced Block Entities (EBE) for it to work (https://modrinth.com/mod/ebe).

Nostalgic Tweaks is also not a resource pack, it is a mod. It pairs very well with Golden Days and will get you a much closer experience to Beta.

Please do not bring negativity to my resource pack or my community, both of you. This is already in the pack, so I am closing the issue.
