### ISSUE TITLE
[Bug] Grass appears more dull in the latest update

### ISSUE THREAD

**Issue by SoftMittens** [PoeticRainbow/golden-days#41]
Hiya, I noticed that in the latest update grass appears duller in the latest update, being very noticable in the forest biome. I don't know if this was intentional, but it is now inaccurate to grass in beta proper. This might also be effecting foliage in general, so trees and stuff but I haven't looked at that hard enough. Hope I'm not being a bother with this!

Environment:
Mod Loader: Fabric
Minecraft Version: 1.20.1
Are you using OptiFine?: No
What other mods are you using?: Nostalgic Tweaks

And here's an image showing the difference, all taken within a forest biome:
![difference](https://github.com/PoeticRainbow/golden-days/assets/148761302/e3519924-421b-4b43-866f-1bca2c6da127)

**Comment by PoeticRainbow** [comment]
This was an unintended change. I attempted to smooth out my colormaps to make the pack more compatible with Modern Beta but it seems the Forest was picking from an area I blurred. I will address this soon.

**Comment by SoftMittens** [comment]
Thank you!
