### ISSUE TITLE
[Bug] Sounds Are Incompatible with NostalgicTweaks

### ISSUE THREAD

**Issue by jlaine3333** [PoeticRainbow/golden-days#44]
**Description of the bug**:
When using NostalgicTweaks, certain sounds are doubled in volume or sounds will play over the wrong sound. For instance, when leaving the hurt sound as Modern in NT, this pack will still play the old hurt sound OVER the modern hurt sound.

**Environment**:
Mod Loader (Forge, Fabric): Fabric
Minecraft Version (1.19.4, 1.20, etc.): 1.20.1
Are you using OptiFine? (Yes/No): No
What other mods are you using? (List): Sodium, NostalgicTweaks, Modern Beta

**Please attach screenshots if applicable**:
n/a

**Comment by PoeticRainbow** [comment]
Golden Days provides the old hurt sound in the Vanilla location and then replaces specialized hurt sounds using the sounds.json
Not sure how Nostalgic Tweaks is implementing it. Adrenix uses Golden Days when he tests the mod.

Just for testing sake, does putting Fabric Mods above Golden Days in the resource pack picker change the behavior?
![image](https://github.com/PoeticRainbow/golden-days/assets/46388705/292b2164-65d3-440e-83c9-f4d410900695)
