### ISSUE TITLE
✨[Feature] Make alpha leaves and grass have a different alpha themed colors in different biomes

### ISSUE THREAD

**Issue by User4716** [PoeticRainbow/golden-days#45]
### I just had a simple idea that the alpha texture pack leaves and grass of different biomes should be different colors. 

Even though some people still prefer the full bright green leaves and grass everywhere even in the new biomes, I think if the alpha versions had jungles and acacia trees for example, they would have a different color than the bright green. 

I have tested the current alpha pack and I went to many biomes and the terrain coloring just looks out of place. The only biome that looks good with the alpha pack is the plains biome since that is the biome the bright green color was meant for in the first place.
‎ 
‎ 
‎ 
I think the maker of this resource pack should make a dedicated pack, or update the existing alpha pack to experiment with new colors for leaves and grass that fit the new biomes better, while making it look like they would be used in old alpha versions. (Since bright green does not fit every biome as I said)

And to clear up this, the beta pack is a whole different thing, it doesn't feel like alpha because it doesn't have the high contrast colors. 
So don't just say: "If you want different colors, then use the beta pack."

Alright, so what do you think? Please comment if you agree or have something to say 👍

**Comment by alphabetlorefan2003** [comment]
I don't think so

**Comment by alphabetlorefan2003** [comment]
the bright green colors doesnt fit in the biome but at least make them look as close

**Comment by PoeticRainbow** [comment]
Technically this is partially implemented in the Alpha Addon as I have different colors for different leaf types.
