### ISSUE TITLE
[Bug] Incompatible with LambDynamicLights mod

### ISSUE THREAD

**Issue by krnlexception** [PoeticRainbow/golden-days#52]
**Description of the bug**:
Using base pack causes LambDynamicLights mod to not show dynamic lights

**Environment**:
Mod Loader (Forge, Fabric): Fabric
Minecraft Version (1.19.4, 1.20, etc.): 1.20.4
Are you using OptiFine? (Yes/No): No
What other mods are you using? (List): Fabulously Optimized 5.8.0-beta.12
  [✔] animatica-0.6+1.20
  [✔] bettermounthud-1.2.2
  [✔] BetterPingDisplay-Fabric-1.20.4-1.1.1
  [✔] borderless-mining-1.1.9+1.20.2
  [✔] capes-1.5.3+1.20.2-fabric
  [✔] cloth-config-13.0.121-fabric
  [✔] continuity-3.0.0-beta.4+1.20.2
  [✔] Controlify-1.8.1+1.20.4
  [✔] Craftify-1.20.4-1.14.0-fabric
  [✔] CraftPresence-2.2.3+1.20.2
  [✔] Debugify-1.20.4+1.0
  [✔] dynamic-fps-3.4.2+minecraft-1.20.4-fabric
  [✔] e4mc-4.0.1+1.19.4-fabric
  [✔] enhancedblockentities-0.9.1+1.20.2
  [✔] entity_model_features_fabric_1.20.4-1.3
  [✔] entity_texture_features_fabric_1.20.4-5.2.3
  [✔] entityculling-fabric-1.6.3.1-mc1.20.4
  [✔] fabric-api-0.96.11+1.20.4
  [✔] fabric-language-kotlin-1.10.19+kotlin.1.9.23
  [✔] fabricskyboxes-0.7.3+mc1.20.2
  [✔] fabrishot-1.12.1
  [✔] fastquit-3.0.0+1.20.4
  [✔] ferritecore-6.0.3-fabric
  [✔] fsb-interop-1.3.6+mc1.20.2-build.52
  [✔] ImmediatelyFast-Fabric-1.2.10+1.20.4
  [✔] indium-1.0.30+mc1.20.4
  [✔] iris-mc1.20.4-1.6.17
  [✔] lambdynamiclights-2.3.4+1.20.4
  [✔] language-reload-1.5.10+1.20.3
  [✔] lithium-fabric-mc1.20.4-0.12.1
  [✔] main-menu-credits-1.1.2
  [✔] mixintrace-1.1.1+1.17
  [✔] ModDetectionPreventer+1.20.4-1.1.0
  [✔] modelfix-1.14-fabric
  [✔] modernfix-fabric-5.14.0+mc1.20.4
  [✔] modmenu-9.0.0
  [✔] morechathistory-1.3.0
  [✔] moreculling-1.20.4-0.22.1
  [✔] NoChatReports-FABRIC-1.20.4-v2.5.0
  [✔] nvidium-0.2.6-beta
  [✔] optigui-2.3.0-alpha.2
  [✔] paginatedadvancements-2.4.2
  [✔] puzzle-1.6.1+1.20.4
  [✔] reeses_sodium_options-1.7.2+mc1.20.4-build.102
  [✔] rrls-4.0.2+mc1.20.4-fabric
  [✔] sodium-extra-0.5.4+mc1.20.4-build.116
  [✔] sodium-fabric-0.5.8+mc1.20.4
  [✔] Squeedometer-1.1.7
  [✔] status-effect-bars-1.0.4
  [✔] Xaeros_Minimap_24.0.2_Fabric_1.20.4
  [✔] XaerosWorldMap_1.38.1_Fabric_1.20.4
  [✔] yet-another-config-lib-fabric-3.3.2+1.20.4
  [✔] yosbr-0.1.2
  [✔] Zoomify-2.13.0

**Please attach screenshots if applicable**:
With base pack:
![2024-04-23_15 49 11](https://github.com/PoeticRainbow/golden-days/assets/31414969/48807b6d-3587-471e-b08d-74e15d484586)

Without base:
![2024-04-23_15 48 53](https://github.com/PoeticRainbow/golden-days/assets/31414969/8c55d0f0-a729-4f2a-8521-38431a6222cd)

Mod settings:
![2024-04-23_15 50 14](https://github.com/PoeticRainbow/golden-days/assets/31414969/0f77dbf7-60f1-4a81-81fd-547b9c995c2a)

**Comment by PoeticRainbow** [comment]
Does this still occur with only Golden Days and LambDynamicLights?

**Comment by krnlexception** [comment]
Hello, no, it doesn't on 1.10.1. Sorry for not responding for quite some time.
