### ISSUE TITLE
[Bug] [1.20+] Main menu Minecraft logo has incorrect dimensions due to scaling changes in the newer versions of the game.

### ISSUE THREAD

**Issue by VOLKOUL** [PoeticRainbow/golden-days#54]
In 1.20 the Minecraft logo in the main menu (as well as the edition text and splash text placement) was changed ALONG with the "box" in which the logo is contained or, in other words, the space available to display said logo. Now it's less wide (height was not changed). While you can accurately match the edition text with how the old one used to be by editing the texture files, the same can't be said about the logo. Let's say you have a 1920x1080 monitor and have set the GUI scale to 3. The old logo had 549 pixels till the edge of the screen, while the new scaling only allows for a max of 576 pixels. Therefore, the logo will appear compressed/squashed. You can't match the proportions without modifying the game itself and the logo won't align properly with the edition text. (I've tried) The only solution I found was to use the Fancy Menu mod and replicate everything there. That way I could return the splash text to the correct position, too. I don't think you can do anything about it, but it's worth letting you know.

Original look:
![Screenshot (936)](https://github.com/PoeticRainbow/golden-days/assets/97387920/50922f81-0151-4d48-b08c-a07c09338e54)

New scaling:
![MINECRAFTtitlescreen1201](https://github.com/PoeticRainbow/golden-days/assets/97387920/b8cf16b5-3d35-47c1-94d0-3dd8de86f146)

Fixed look: (Fancy menu)
![Screenshot (1036)](https://github.com/PoeticRainbow/golden-days/assets/97387920/7348730d-420f-4985-bb8d-4a1e94327ff5)

Tutorial:
![FMoldlogo](https://github.com/PoeticRainbow/golden-days/assets/97387920/dec57d2f-33ef-443f-b2b0-f4b88d1e4b24)

**Comment by PoeticRainbow** [comment]
Unfortunately don't have a good solution for this at the moment.

**Comment by VOLKOUL** [comment]
Somebody in the Nostalgic Tweaks discord said it could (possibly) be fixed by using Minecraft's core shader system. Highly hypothetical though.

**Comment by PoeticRainbow** [comment]
Unfortunately I don't know GLSL and right now it is out of the scope of what I'm looking to learn.
