### ISSUE TITLE
[Feature] Change dropped item thin thickness to 3D thickness

### ISSUE THREAD

**Issue by SanguineWaters** [PoeticRainbow/golden-days#55]
**Hello, I noticed that dropped items are just a thin plane like flower/grass textures when Golden days is loaded. I'm wondering if there is a way and where to configure that after attempting to find it**:

**Thin thickness with Golden Days loaded with programmer art**
![2024-08-02_20 03 16](https://github.com/user-attachments/assets/e3cb2d52-3a5a-488c-85cc-452b739cbcd4)

**Regular thickness with Golden Days unloaded**
![2024-08-02_20 03 35](https://github.com/user-attachments/assets/04fcac4a-b93f-4c5c-af0b-d8ba03332592)

Thank you in advance

**Comment by PoeticRainbow** [comment]
This is intentional. If you don't like it then remove the "ground" category from the generated.json
