### ISSUE TITLE
[Bug] Golden Days Alpha turns EVERYTHING green.

### ISSUE THREAD

**Issue by jacklollz2** [PoeticRainbow/golden-days#57]
**Description of the bug**:
Every biome becomes green, including savannah and etc.

**Environment**:
Mod Loader (Forge, Fabric): Quilt (Fabric)
Minecraft Version (1.19.4, 1.20, etc.): 1.20.1
Are you using OptiFine? (Yes/No): No (Sodium+Iridium+Iris)
What other mods are you using? (List): 
Mods:
- Remove Reloading Screen
- Language Reload

Datapacks:
- Explorify
- Dungeons and Taverns

**Please attach screenshots if applicable**:
![image](https://github.com/user-attachments/assets/4f08ee7a-ce9d-4cff-b120-37c60b6ffdc1)

**Comment by SouperAmng** [comment]
This is not a bug. That's just how pre-v1.2.0 Alpha looked.
Here's a screenshot from Minecraft Wiki:
![Alpha_v1 1 2_01](https://github.com/user-attachments/assets/2192c777-c21c-4473-9699-c73a2c0dffbd)

**Comment by jacklollz2** [comment]
I want the alpha green for forests and such, but not for everywhere else. I want Savannah and Swamps to look correct.

**Comment by SouperAmng** [comment]
I mean, early and mid-Alpha didn't really have biomes at all, it had generation presets, like forests, beaches with cacti or not, etc.

**Comment by jacklollz2** [comment]
I understand, but I like the green for the forests only

**Comment by PoeticRainbow** [comment]
This is completely intentional and unfortunately your use case just isn't going to be supported by me.
