### ISSUE TITLE
[Bug] Chest and ender chest texture broken

### ISSUE THREAD

**Issue by benjipkc** [PoeticRainbow/golden-days#58]
**Description of the bug**:
chest/ender chest texture is missing textures :( photo attached 

![chest](https://github.com/user-attachments/assets/2b507cd7-7652-4931-b6a5-ab37230022f0)
![chest 2](https://github.com/user-attachments/assets/e64dc7e0-3751-4cfd-a54b-47c38eac0240)

**Environment**:
Mod Loader - Fabric
Minecraft Version - 1.21.1
Are you using OptiFine? - No
What other mods are you using? (List):
![mods](https://github.com/user-attachments/assets/01f7edea-f8a7-4841-b8de-9c58c2de8a4a)

**Comment by PoeticRainbow** [comment]
Can you send the order of your resource packs?

**Comment by benjipkc** [comment]
sorry for the late reply

![resource packs](https://github.com/user-attachments/assets/490c0802-d231-426f-9c95-338ea3f7b26a)

**Comment by PoeticRainbow** [comment]
I cannot reproduce this issue unfortunately. Try updating your EMF.

![2024-10-21_16 27 25](https://github.com/user-attachments/assets/932da265-36dc-4b75-91f1-353a6ae2ab45)

Minecraft 1.21.1
- Continuity [3\.0\.0\-beta\.5\+1\.21]
- Entity Model Features [2\.2\.6]
- Entity Texture Features [6\.2\.5]
- Fabric API [0\.106\.0\+1\.21\.1]
- Iris [1\.8\.0\-beta\.4\+mc1\.21\.1]
- Lithium [0\.14\.0\-snapshot\+mc1\.21\.1\-build\.88]
- Mod Menu [11\.0\.3]
- Placeholder API [2\.4\.1\+1\.21]
- Polytone [1\.21\-2\.4\.26]
- Sodium [0\.6\.0\-beta\.2\+mc1\.21\.1]

**Comment by benjipkc** [comment]
that worked! i feel foolish i never considered that, thank you!

**Comment by benjipkc** [comment]
that worked! thank you so much!
